<a href="https://colab.research.google.com/github/shreyus3003/Deep_Learning/blob/master/numpy_prac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [30]:
a = np.array([0,1,2])
b = np.array([5,5,5])
print(a + b)
print(a+5)

[5 6 7]
[5 6 7]


In [31]:
M = np.ones((3,3))
print(M) 
M +a

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [32]:
a = np.arange(3)
c = np.arange(4)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)
print(c)

[0 1 2]
[[0]
 [1]
 [2]]
[0 1 2 3]


In [33]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [34]:
M = np.ones((2,3))
a = np.arange(3)
M.shape
a.shape

(3,)

In [35]:
M +a 

array([[1., 2., 3.],
       [1., 2., 3.]])

In [36]:
M = np.array((3,2))
a = np.arange(3)
M + a[:, np.newaxis]

array([[3, 2],
       [4, 3],
       [5, 4]])

In [37]:
a = np.arange(3).reshape((3,1))
b = np.arange(3)
print(a)
print(b)
print(a * b)
print(a +b)

[[0]
 [1]
 [2]]
[0 1 2]
[[0 0 0]
 [0 1 2]
 [0 2 4]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [38]:
X = np.random.random((10,3))
X

array([[0.51733612, 0.96174194, 0.41414203],
       [0.98331111, 0.16017574, 0.98592421],
       [0.22991048, 0.50023615, 0.49669132],
       [0.29807077, 0.94581662, 0.45310612],
       [0.03504082, 0.28947966, 0.97793944],
       [0.04192468, 0.0967417 , 0.17899729],
       [0.46415085, 0.42392471, 0.84761263],
       [0.33765153, 0.3838545 , 0.19674133],
       [0.92149918, 0.32037187, 0.52480403],
       [0.42241455, 0.24862208, 0.33162141]])

In [39]:
xmean = X.mean(0)
xmean

array([0.42513101, 0.4330965 , 0.54075798])

In [40]:
xcen =X-xmean
xcen

array([[ 0.09220511,  0.52864545, -0.12661596],
       [ 0.5581801 , -0.27292076,  0.44516623],
       [-0.19522053,  0.06713966, -0.04406667],
       [-0.12706024,  0.51272012, -0.08765186],
       [-0.39009019, -0.14361684,  0.43718146],
       [-0.38320633, -0.3363548 , -0.36176069],
       [ 0.03901984, -0.00917178,  0.30685465],
       [-0.08747948, -0.049242  , -0.34401665],
       [ 0.49636817, -0.11272462, -0.01595395],
       [-0.00271646, -0.18447442, -0.20913657]])

In [43]:
x1 = np.random.randint(10,size=(3,4,5))
x1

array([[[2, 9, 1, 8, 6],
        [1, 3, 7, 9, 9],
        [8, 9, 4, 0, 1],
        [0, 7, 0, 2, 2]],

       [[4, 2, 8, 4, 4],
        [8, 2, 4, 7, 2],
        [4, 1, 9, 3, 7],
        [5, 0, 6, 3, 6]],

       [[0, 3, 0, 6, 5],
        [2, 2, 4, 9, 0],
        [7, 7, 7, 3, 6],
        [7, 3, 2, 1, 8]]])

In [50]:
x2 = np.random.randint(20, size=(3,4))
x2

array([[ 8,  0,  7, 14],
       [12,  3,  2, 11],
       [18, 13,  9,  1]])

In [52]:
x = np.arange(10)
print(x)
x[5::-2]

[0 1 2 3 4 5 6 7 8 9]


array([5, 3, 1])

In [54]:
x2[::-1,::-2]

array([[ 1, 13],
       [11,  3],
       [14,  0]])